"""Build the GitHub reading table of contents from the canonical book manifest."""

from __future__ import annotations

import argparse

from build_markdown import ROOT, chapter_title, manifest_entries


OUTPUT = ROOT / "book" / "CONTENTS.md"


def render() -> str:
    lines = [
        "<!-- Generated by scripts/build_contents.py from book/manifest.txt; do not edit. -->",
        "# 按书的顺序阅读",
        "",
        "这里是 GitHub 上的完整阅读目录。章节正文只在各自的 Markdown 文件中维护；",
        "本页、[在线阅读站](https://books.aimake.cc/)和 PDF 使用同一份书稿清单。",
        "也可以从[按问题进入](../README.md#从问题进入)开始，或下载[可携带 Markdown 阅读包](README.md#markdown-阅读包)。",
        "",
    ]
    section = ""
    count = 0
    for kind, value in manifest_entries():
        next_section = {"front": "卷首", "back": "卷末"}.get(kind)
        if kind == "part":
            next_section = value
        if next_section and next_section != section:
            if lines[-1]:
                lines.append("")
            lines.extend([f"## {next_section}", ""])
            section = next_section
        if kind != "part":
            count += 1
            lines.append(f"{count}. [{chapter_title(value)}](../{value})")
    lines.extend([
        "",
        "---",
        "",
        "读系统篇时请留意文内固定源码版本、证据和未验证范围；",
        "本目录是阅读顺序，不是正式出版验收记录。",
        "[当前状态与缺口](../docs/roadmap.md) · [写作与校稿方法](../docs/editorial-plan.md)",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the tracked contents are stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("book/CONTENTS.md is stale; run python3 scripts/build_contents.py")
        print("GitHub contents match book/manifest.txt")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
